{
    "environment_setup": {
        "create_conda_env": {
            "stdout": "Collecting package metadata (repodata.json): ...working... done\nSolving environment: ...working... done\n\n## Package Plan ##\n\n  environment location: C:\\Users\\smith\\Anaconda3\\envs\\myenv\n\n  added / updated specs:\n    - python=3.8\n\n\nThe following NEW packages will be INSTALLED:\n\n  ca-certificates    pkgs/main/win-64::ca-certificates-2024.11.26-haa95532_0\n  libffi             pkgs/main/win-64::libffi-3.4.4-hd77b12b_1\n  openssl            pkgs/main/win-64::openssl-3.0.15-h827c3e9_0\n  pip                pkgs/main/win-64::pip-24.2-py38haa95532_0\n  python             pkgs/main/win-64::python-3.8.20-h8205438_0\n  setuptools         pkgs/main/win-64::setuptools-75.1.0-py38haa95532_0\n  sqlite             pkgs/main/win-64::sqlite-3.45.3-h2bbff1b_0\n  vc                 pkgs/main/win-64::vc-14.40-h2eaa2aa_1\n  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.40.33807-h98bb1dd_1\n  wheel              pkgs/main/win-64::wheel-0.44.0-py38haa95532_0\n\n\nPreparing transaction: ...working... done\nVerifying transaction: ...working... done\nExecuting transaction: ...working... done\n#\n# To activate this environment, use\n#\n#     $ conda activate myenv\n#\n# To deactivate an active environment, use\n#\n#     $ conda deactivate\n\n",
            "stderr": "\n\n==> WARNING: A newer version of conda exists. <==\n  current version: 4.8.2\n  latest version: 24.11.0\n\nPlease update conda by running\n\n    $ conda update -n base -c defaults conda\n\n\n",
            "returncode": 0
        },
        "activate_conda_env": {
            "stdout": "",
            "stderr": "",
            "returncode": 0
        },
        "pip_install": {
            "stdout": "Collecting torch (from -r filtered_requirements.txt (line 1))\n\n  Using cached torch-2.4.1-cp38-cp38-win_amd64.whl.metadata (27 kB)\n\nCollecting transformers (from -r filtered_requirements.txt (line 2))\n\n  Using cached transformers-4.46.3-py3-none-any.whl.metadata (44 kB)\n\nCollecting datasets (from -r filtered_requirements.txt (line 3))\n\n  Using cached datasets-3.1.0-py3-none-any.whl.metadata (20 kB)\n\nCollecting evaluate (from -r filtered_requirements.txt (line 4))\n\n  Using cached evaluate-0.4.3-py3-none-any.whl.metadata (9.2 kB)\n\nCollecting filelock (from torch->-r filtered_requirements.txt (line 1))\n\n  Using cached filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)\n\nCollecting typing-extensions>=4.8.0 (from torch->-r filtered_requirements.txt (line 1))\n\n  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)\n\nCollecting sympy (from torch->-r filtered_requirements.txt (line 1))\n\n  Using cached sympy-1.13.3-py3-none-any.whl.metadata (12 kB)\n\nCollecting networkx (from torch->-r filtered_requirements.txt (line 1))\n\n  Using cached networkx-3.1-py3-none-any.whl.metadata (5.3 kB)\n\nCollecting jinja2 (from torch->-r filtered_requirements.txt (line 1))\n\n  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)\n\nCollecting fsspec (from torch->-r filtered_requirements.txt (line 1))\n\n  Using cached fsspec-2024.10.0-py3-none-any.whl.metadata (11 kB)\n\nCollecting huggingface-hub<1.0,>=0.23.2 (from transformers->-r filtered_requirements.txt (line 2))\n\n  Using cached huggingface_hub-0.26.3-py3-none-any.whl.metadata (13 kB)\n\nCollecting numpy>=1.17 (from transformers->-r filtered_requirements.txt (line 2))\n\n  Using cached numpy-1.24.4-cp38-cp38-win_amd64.whl.metadata (5.6 kB)\n\nCollecting packaging>=20.0 (from transformers->-r filtered_requirements.txt (line 2))\n\n  Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)\n\nCollecting pyyaml>=5.1 (from transformers->-r filtered_requirements.txt (line 2))\n\n  Using cached PyYAML-6.0.2-cp38-cp38-win_amd64.whl.metadata (2.1 kB)\n\nCollecting regex!=2019.12.17 (from transformers->-r filtered_requirements.txt (line 2))\n\n  Using cached regex-2024.11.6-cp38-cp38-win_amd64.whl.metadata (41 kB)\n\nCollecting requests (from transformers->-r filtered_requirements.txt (line 2))\n\n  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)\n\nCollecting tokenizers<0.21,>=0.20 (from transformers->-r filtered_requirements.txt (line 2))\n\n  Using cached tokenizers-0.20.3-cp38-none-win_amd64.whl.metadata (6.9 kB)\n\nCollecting safetensors>=0.4.1 (from transformers->-r filtered_requirements.txt (line 2))\n\n  Using cached safetensors-0.4.5-cp38-none-win_amd64.whl.metadata (3.9 kB)\n\nCollecting tqdm>=4.27 (from transformers->-r filtered_requirements.txt (line 2))\n\n  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)\n\nCollecting pyarrow>=15.0.0 (from datasets->-r filtered_requirements.txt (line 3))\n\n  Using cached pyarrow-17.0.0-cp38-cp38-win_amd64.whl.metadata (3.4 kB)\n\nCollecting dill<0.3.9,>=0.3.0 (from datasets->-r filtered_requirements.txt (line 3))\n\n  Using cached dill-0.3.8-py3-none-any.whl.metadata (10 kB)\n\nCollecting pandas (from datasets->-r filtered_requirements.txt (line 3))\n\n  Using cached pandas-2.0.3-cp38-cp38-win_amd64.whl.metadata (18 kB)\n\nCollecting xxhash (from datasets->-r filtered_requirements.txt (line 3))\n\n  Using cached xxhash-3.5.0-cp38-cp38-win_amd64.whl.metadata (13 kB)\n\nCollecting multiprocess<0.70.17 (from datasets->-r filtered_requirements.txt (line 3))\n\n  Using cached multiprocess-0.70.16-py38-none-any.whl.metadata (7.1 kB)\n\nCollecting fsspec (from torch->-r filtered_requirements.txt (line 1))\n\n  Using cached fsspec-2024.9.0-py3-none-any.whl.metadata (11 kB)\n\nCollecting aiohttp (from datasets->-r filtered_requirements.txt (line 3))\n\n  Using cached aiohttp-3.10.11-cp38-cp38-win_amd64.whl.metadata (8.0 kB)\n\nCollecting aiohappyeyeballs>=2.3.0 (from aiohttp->datasets->-r filtered_requirements.txt (line 3))\n\n  Downloading aiohappyeyeballs-2.4.4-py3-none-any.whl.metadata (6.1 kB)\n\nCollecting aiosignal>=1.1.2 (from aiohttp->datasets->-r filtered_requirements.txt (line 3))\n\n  Using cached aiosignal-1.3.1-py3-none-any.whl.metadata (4.0 kB)\n\nCollecting attrs>=17.3.0 (from aiohttp->datasets->-r filtered_requirements.txt (line 3))\n\n  Using cached attrs-24.2.0-py3-none-any.whl.metadata (11 kB)\n\nCollecting frozenlist>=1.1.1 (from aiohttp->datasets->-r filtered_requirements.txt (line 3))\n\n  Using cached frozenlist-1.5.0-cp38-cp38-win_amd64.whl.metadata (14 kB)\n\nCollecting multidict<7.0,>=4.5 (from aiohttp->datasets->-r filtered_requirements.txt (line 3))\n\n  Using cached multidict-6.1.0-cp38-cp38-win_amd64.whl.metadata (5.1 kB)\n\nCollecting yarl<2.0,>=1.12.0 (from aiohttp->datasets->-r filtered_requirements.txt (line 3))\n\n  Using cached yarl-1.15.2-cp38-cp38-win_amd64.whl.metadata (58 kB)\n\nCollecting async-timeout<6.0,>=4.0 (from aiohttp->datasets->-r filtered_requirements.txt (line 3))\n\n  Using cached async_timeout-5.0.1-py3-none-any.whl.metadata (5.1 kB)\n\nCollecting charset-normalizer<4,>=2 (from requests->transformers->-r filtered_requirements.txt (line 2))\n\n  Using cached charset_normalizer-3.4.0-cp38-cp38-win_amd64.whl.metadata (34 kB)\n\nCollecting idna<4,>=2.5 (from requests->transformers->-r filtered_requirements.txt (line 2))\n\n  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)\n\nCollecting urllib3<3,>=1.21.1 (from requests->transformers->-r filtered_requirements.txt (line 2))\n\n  Using cached urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)\n\nCollecting certifi>=2017.4.17 (from requests->transformers->-r filtered_requirements.txt (line 2))\n\n  Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)\n\nCollecting colorama (from tqdm>=4.27->transformers->-r filtered_requirements.txt (line 2))\n\n  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)\n\nCollecting MarkupSafe>=2.0 (from jinja2->torch->-r filtered_requirements.txt (line 1))\n\n  Using cached MarkupSafe-2.1.5-cp38-cp38-win_amd64.whl.metadata (3.1 kB)\n\nCollecting python-dateutil>=2.8.2 (from pandas->datasets->-r filtered_requirements.txt (line 3))\n\n  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)\n\nCollecting pytz>=2020.1 (from pandas->datasets->-r filtered_requirements.txt (line 3))\n\n  Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)\n\nCollecting tzdata>=2022.1 (from pandas->datasets->-r filtered_requirements.txt (line 3))\n\n  Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)\n\nCollecting mpmath<1.4,>=1.1.0 (from sympy->torch->-r filtered_requirements.txt (line 1))\n\n  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)\n\nCollecting six>=1.5 (from python-dateutil>=2.8.2->pandas->datasets->-r filtered_requirements.txt (line 3))\n\n  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)\n\nCollecting propcache>=0.2.0 (from yarl<2.0,>=1.12.0->aiohttp->datasets->-r filtered_requirements.txt (line 3))\n\n  Using cached propcache-0.2.0-cp38-cp38-win_amd64.whl.metadata (7.9 kB)\n\nUsing cached torch-2.4.1-cp38-cp38-win_amd64.whl (199.4 MB)\n\nUsing cached transformers-4.46.3-py3-none-any.whl (10.0 MB)\n\nUsing cached datasets-3.1.0-py3-none-any.whl (480 kB)\n\nUsing cached evaluate-0.4.3-py3-none-any.whl (84 kB)\n\nUsing cached dill-0.3.8-py3-none-any.whl (116 kB)\n\nUsing cached fsspec-2024.9.0-py3-none-any.whl (179 kB)\n\nUsing cached aiohttp-3.10.11-cp38-cp38-win_amd64.whl (384 kB)\n\nUsing cached huggingface_hub-0.26.3-py3-none-any.whl (447 kB)\n\nUsing cached multiprocess-0.70.16-py38-none-any.whl (132 kB)\n\nUsing cached numpy-1.24.4-cp38-cp38-win_amd64.whl (14.9 MB)\n\nUsing cached packaging-24.2-py3-none-any.whl (65 kB)\n\nUsing cached pyarrow-17.0.0-cp38-cp38-win_amd64.whl (25.2 MB)\n\nUsing cached PyYAML-6.0.2-cp38-cp38-win_amd64.whl (162 kB)\n\nUsing cached regex-2024.11.6-cp38-cp38-win_amd64.whl (274 kB)\n\nUsing cached requests-2.32.3-py3-none-any.whl (64 kB)\n\nUsing cached safetensors-0.4.5-cp38-none-win_amd64.whl (286 kB)\n\nUsing cached tokenizers-0.20.3-cp38-none-win_amd64.whl (2.4 MB)\n\nUsing cached tqdm-4.67.1-py3-none-any.whl (78 kB)\n\nUsing cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)\n\nUsing cached filelock-3.16.1-py3-none-any.whl (16 kB)\n\nUsing cached jinja2-3.1.4-py3-none-any.whl (133 kB)\n\nUsing cached networkx-3.1-py3-none-any.whl (2.1 MB)\n\nUsing cached pandas-2.0.3-cp38-cp38-win_amd64.whl (10.8 MB)\n\nUsing cached sympy-1.13.3-py3-none-any.whl (6.2 MB)\n\nUsing cached xxhash-3.5.0-cp38-cp38-win_amd64.whl (30 kB)\n\nDownloading aiohappyeyeballs-2.4.4-py3-none-any.whl (14 kB)\n\nUsing cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)\n\nUsing cached async_timeout-5.0.1-py3-none-any.whl (6.2 kB)\n\nUsing cached attrs-24.2.0-py3-none-any.whl (63 kB)\n\nUsing cached certifi-2024.8.30-py3-none-any.whl (167 kB)\n\nUsing cached charset_normalizer-3.4.0-cp38-cp38-win_amd64.whl (101 kB)\n\nUsing cached frozenlist-1.5.0-cp38-cp38-win_amd64.whl (51 kB)\n\nUsing cached idna-3.10-py3-none-any.whl (70 kB)\n\nUsing cached MarkupSafe-2.1.5-cp38-cp38-win_amd64.whl (17 kB)\n\nUsing cached mpmath-1.3.0-py3-none-any.whl (536 kB)\n\nUsing cached multidict-6.1.0-cp38-cp38-win_amd64.whl (28 kB)\n\nUsing cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)\n\nUsing cached pytz-2024.2-py2.py3-none-any.whl (508 kB)\n\nUsing cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)\n\nUsing cached urllib3-2.2.3-py3-none-any.whl (126 kB)\n\nUsing cached yarl-1.15.2-cp38-cp38-win_amd64.whl (84 kB)\n\nUsing cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)\n\nUsing cached propcache-0.2.0-cp38-cp38-win_amd64.whl (45 kB)\n\nUsing cached six-1.16.0-py2.py3-none-any.whl (11 kB)\n\nInstalling collected packages: pytz, mpmath, xxhash, urllib3, tzdata, typing-extensions, sympy, six, safetensors, regex, pyyaml, propcache, packaging, numpy, networkx, MarkupSafe, idna, fsspec, frozenlist, filelock, dill, colorama, charset-normalizer, certifi, attrs, async-timeout, aiohappyeyeballs, tqdm, requests, python-dateutil, pyarrow, multiprocess, multidict, jinja2, aiosignal, yarl, torch, pandas, huggingface-hub, tokenizers, aiohttp, transformers, datasets, evaluate\n\nSuccessfully installed MarkupSafe-2.1.5 aiohappyeyeballs-2.4.4 aiohttp-3.10.11 aiosignal-1.3.1 async-timeout-5.0.1 attrs-24.2.0 certifi-2024.8.30 charset-normalizer-3.4.0 colorama-0.4.6 datasets-3.1.0 dill-0.3.8 evaluate-0.4.3 filelock-3.16.1 frozenlist-1.5.0 fsspec-2024.9.0 huggingface-hub-0.26.3 idna-3.10 jinja2-3.1.4 mpmath-1.3.0 multidict-6.1.0 multiprocess-0.70.16 networkx-3.1 numpy-1.24.4 packaging-24.2 pandas-2.0.3 propcache-0.2.0 pyarrow-17.0.0 python-dateutil-2.9.0.post0 pytz-2024.2 pyyaml-6.0.2 regex-2024.11.6 requests-2.32.3 safetensors-0.4.5 six-1.16.0 sympy-1.13.3 tokenizers-0.20.3 torch-2.4.1 tqdm-4.67.1 transformers-4.46.3 typing-extensions-4.12.2 tzdata-2024.2 urllib3-2.2.3 xxhash-3.5.0 yarl-1.15.2\n\n\n",
            "stderr": "",
            "returncode": 0
        },
        "example_usage.sh": [
            {
                "command": "python main.py --learning_rate 0.01 --num_epochs 10 --batch_size 16 --embedding_dim 300 --kernel_sizes 3 4 5 --max_length 50 --save_every_n_epoch 2 --train --gpu --output_dir './outputs' --train_log_per_k_batch 20 --random_seed 20",
                "result": {
                    "stdout": "",
                    "stderr": "ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['python', 'main.py', '--learning_rate', '0.01', '--num_epochs', '10', '--batch_size', '16', '--embedding_dim', '300', '--kernel_sizes', '3', '4', '5', '--max_length', '50', '--save_every_n_epoch', '2', '--train', '--gpu', '--output_dir', \"'./outputs'\", '--train_log_per_k_batch', '20', '--random_seed', '20']' command failed.  (See above for error)\nTraceback (most recent call last):\n\n  File \"main.py\", line 64, in <module>\n\n    main()\n\n  File \"main.py\", line 50, in main\n\n    train_data, val_data, test_data = data_loader.load_data()\n\n  File \"C:\\Users\\smith\\code\\autoSWE\\system\\outputs\\v3\\TextCNN\\data\\data_loader.py\", line 20, in load_data\n\n    train_data = self.preprocess_data(train_dataset)\n\n  File \"C:\\Users\\smith\\code\\autoSWE\\system\\outputs\\v3\\TextCNN\\data\\data_loader.py\", line 30, in preprocess_data\n\n    tokenized_datasets = dataset.map(tokenize_function, batched=True)\n\nAttributeError: 'Subset' object has no attribute 'map'\n\n\n",
                    "returncode": 0
                }
            },
            {
                "command": "python main.py --test --gpu --output_dir './outputs'",
                "result": {
                    "stdout": "",
                    "stderr": "ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['python', 'main.py', '--test', '--gpu', '--output_dir', \"'./outputs'\"]' command failed.  (See above for error)\nTraceback (most recent call last):\n\n  File \"main.py\", line 64, in <module>\n\n    main()\n\n  File \"main.py\", line 50, in main\n\n    train_data, val_data, test_data = data_loader.load_data()\n\n  File \"C:\\Users\\smith\\code\\autoSWE\\system\\outputs\\v3\\TextCNN\\data\\data_loader.py\", line 20, in load_data\n\n    train_data = self.preprocess_data(train_dataset)\n\n  File \"C:\\Users\\smith\\code\\autoSWE\\system\\outputs\\v3\\TextCNN\\data\\data_loader.py\", line 30, in preprocess_data\n\n    tokenized_datasets = dataset.map(tokenize_function, batched=True)\n\nAttributeError: 'Subset' object has no attribute 'map'\n\n\n",
                    "returncode": 0
                }
            }
        ]
    },
    "acceptance_tests": {
        "stdout": "",
        "stderr": "ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['python', '-m', 'unittest', 'tests/acceptance/test_features.py']' command failed.  (See above for error)\nFF\n\n======================================================================\n\nFAIL: test_testing_mode (tests.acceptance.test_features.TestTextCNNAcceptance)\n\n----------------------------------------------------------------------\n\nTraceback (most recent call last):\n\n  File \"C:\\Users\\smith\\code\\autoSWE\\system\\outputs\\v3\\TextCNN\\tests\\acceptance\\test_features.py\", line 50, in test_testing_mode\n\n    self.assertIn('Test Accuracy:', output)\n\nAssertionError: 'Test Accuracy:' not found in ''\n\n\n\n======================================================================\n\nFAIL: test_training_mode (tests.acceptance.test_features.TestTextCNNAcceptance)\n\n----------------------------------------------------------------------\n\nTraceback (most recent call last):\n\n  File \"C:\\Users\\smith\\code\\autoSWE\\system\\outputs\\v3\\TextCNN\\tests\\acceptance\\test_features.py\", line 36, in test_training_mode\n\n    self.assertIn('Loss:', output)\n\nAssertionError: 'Loss:' not found in ''\n\n\n\n----------------------------------------------------------------------\n\nRan 2 tests in 18.288s\n\n\n\nFAILED (failures=2)\n\n\n",
        "returncode": 0
    },
    "unit_tests": {
        "run_tests": {
            "stdout": "",
            "stderr": "ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['coverage', 'run', '-m', 'unittest', 'tests/unit/test_module.py']' command failed.  (See above for error)\nE\n\n======================================================================\n\nERROR: test_module (unittest.loader._FailedTest)\n\n----------------------------------------------------------------------\n\nImportError: Failed to import test module: test_module\n\nTraceback (most recent call last):\n\n  File \"c:\\users\\smith\\anaconda3\\lib\\unittest\\loader.py\", line 154, in loadTestsFromName\n\n    module = __import__(module_name)\n\n  File \"C:\\Users\\smith\\code\\autoSWE\\system\\outputs\\v3\\TextCNN\\tests\\unit\\test_module.py\", line 3, in <module>\n\n    import torch\n\n  File \"c:\\users\\smith\\anaconda3\\lib\\site-packages\\torch\\__init__.py\", line 676, in <module>\n\n    from .storage import _StorageBase, TypedStorage, _LegacyStorage, UntypedStorage\n\n  File \"c:\\users\\smith\\anaconda3\\lib\\site-packages\\torch\\storage.py\", line 11, in <module>\n\n    import numpy as np\n\n  File \"c:\\users\\smith\\anaconda3\\lib\\site-packages\\numpy\\__init__.py\", line 150, in <module>\n\n    from . import core\n\n  File \"c:\\users\\smith\\anaconda3\\lib\\site-packages\\numpy\\core\\__init__.py\", line 68, in <module>\n\n    raise ImportError(msg.format(path))\n\nImportError: Something is wrong with the numpy installation. While importing we detected an older version of numpy in ['c:\\\\users\\\\smith\\\\anaconda3\\\\lib\\\\site-packages\\\\numpy']. One method of fixing this is to repeatedly uninstall numpy until none is found, then reinstall this version.\n\n\n\n\n\n----------------------------------------------------------------------\n\nRan 1 test in 0.000s\n\n\n\nFAILED (errors=1)\n\nc:\\users\\smith\\anaconda3\\lib\\site-packages\\coverage\\control.py:860: CoverageWarning: No data was collected. (no-data-collected)\n\n  self._warn(\"No data was collected.\", slug=\"no-data-collected\")\n\n\n",
            "returncode": 0
        },
        "coverage_report": {
            "stdout": "No data to report.\n\n\n",
            "stderr": "ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['coverage', 'report']' command failed.  (See above for error)\n",
            "returncode": 0
        }
    }
}